---
  - block:
    - name: Make for Debian/Ubuntu
      command: fakeroot ./debian/rules binary
      args:
        chdir: "{{ deb_dir }}"
      environment:
        DEB_BUILD_OPTIONS: 'parallel=8 nocheck'
      become: true

    - name: Install a packages
      apt:
        deb: "{{ item }}"
      with_items: "{{ deb_ovs_packages }}"
      become: true

    - name: Start OVS
      service:
        name: openvswitch-switch
        state: started
        enabled: yes
      become: true

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
