---
- name: Set fact based on OS
  set_fact:
    ovs_dir: "{{ el_dir }}"
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Set fact based on OS
  set_fact:
    ovs_dir: "{{ deb_dir }}"
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Download OVS
  get_url:
    url: "{{ ovs_url }}"
    dest: /tmp/

- name: Install Generic OVS dependencies
  package:
    name: "{{ item }}"
    state: installed
  become: true
  with_items: "{{ generic_deps }}"

- include_tasks: el_prep.yml
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- include_tasks: deb_prep.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Find flow header files
  shell: "find {{ ovs_dir }} -type f -name flow.h"
  register: flow_files
  become: true

- name: Update FLOW MAX MPLS labels
  shell: >
    sed -i 's/define FLOW_MAX_MPLS_LABELS .*/define FLOW_MAX_MPLS_LABELS {{ MAX_MPLS }}/g' {{ item }} &&
    sed -i 's/sizeof(struct flow_tnl) + sizeof(struct flow_nsh) + 300/sizeof(struct flow_tnl) + sizeof(struct flow_nsh) + 284 + (4 * ROUND_UP(FLOW_MAX_MPLS_LABELS, 2))/g' {{ item }}
  with_items: "{{ flow_files.stdout_lines }}"
  become: true

- include_tasks: el_install.yml
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- include_tasks: deb_install.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
